/*
 * File: app/view/sprint/Grid.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Scrum.view.sprint.Grid', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.scrum-sprint-grid',
    title : 'Sprints Overview',
    tools : [
        { type : 'plus', action : 'create', tooltipType : 'title', tooltip : 'Add new sprint'},
        { type : 'refresh', action : 'refresh', tooltipType : 'title', tooltip : 'Refresh overview'}
    ],
    forceFit : true, 

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            columns: [
                {
                    dataIndex: 'name',
                    text: 'Name',
                    type : 'string',
                    groupable : false
                },
                {
                    dataIndex : 'status',
                    type : 'int',
                    text: 'Status',
                    groupable : false,
                },
                {   
                    dataIndex: 'update_time',
                    text: 'Update time',
                    groupable : false,
                    renderer : function(value){
                        return Scrum.util.template.getPostDate(value);
                    }
                }
            ]
        });

        me.callParent(arguments);
    }

});